export const userActionTypes = {
  REQUEST_USER_LIST: 'REQUEST_USER_LIST',
  SUCCESS_GET_USER_LIST: 'SUCCESS_GET_USER_LIST',
  GET_AUTH_USER: 'GET_AUTH_USER',
  REQUEST_AUTH_USER: 'REQUEST_AUTH_USER',
  ERROR_AUTH_USER: 'ERROR_AUTH_USER'
};
