export const actionTypes = {
  REQUEST_TEAM_LIST: 'REQUEST_TEAM_LIST',
  RESOLVE_TEAM_LIST: 'RESOLVE_TEAM_LIST',
  REQUEST_TEAM_OPTIONS: 'REQUEST_TEAM_OPTIONS',
  RESOLVE_TEAM_OPTIONS: 'RESOLVE_TEAM_OPTIONS',
  FAILURE: 'FAILURE'
};