export const roleActionTypes = {
  REQUEST_ROLE_LIST: 'REQUEST_ROLE_LIST',
  RESOLVE_ROLE_LIST: 'RESOLVE_ROLE_LIST',
  REQUEST_ROLE_OPTIONS: 'REQUEST_ROLE_OPTIONS',
  RESOLVE_ROLE_OPTIONS: 'RESOLVE_ROLE_OPTIONS',
  FAILURE_LIST: 'FAILURE_LIST',
  FAILURE_OPTIONS: 'FAILURE_OPTIONS'
};
